apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: jenkins
  name: indy-stress-tester-build
  namespace: nos-automation
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    pushSecret:
      name: kaine-indybot-pull-secret
    to:
      kind: DockerImage
      name: quay.io/kaine/indy-stress-tester:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/shokakucarrier/indy-stress-tester.git
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers: []
